### PR TITLE
Transparent navbar and footer

### PR DESCRIPTION
**Pull request by raffoz**

### CODE REVIEW

**Comment by kleyv** [comment]
@raffoz I thought the goal was to have the text and icons and text on the navbar always visible and just make the background transparent. It seems unnecessary that I have to scroll back up to access the tools in the navbar.
Also use the body of the commit to say **what** you did and **why**. The *how* isn't important.

**Comment by raffoz** [comment]
I just inserted navbar and footer, then with 2 css codes it can be changed
I do not know what was the goal, but simple I added the navbar :)


On August 27, 2020 at 9:56 AM, kleyv (notifications@github.com) wrote:
@raffoz ( https://github.com/raffoz ) I thought the goal was to have the text and icons and text on the navbar always visible and just make the background transparent. It seems unnecessary that I have to scroll back up to access the tools in the navbar.
Also use the body of the commit to say what you did and why. The how isn't important.

**Comment by kleyv** [comment]
Can you change it to not disappear as we scroll down? @raffoz

**Comment by raffoz** [comment]
If you want ok, but we can do whenever, it's one line of code :D


On August 27, 2020 at 10:04 AM, kleyv (notifications@github.com) wrote:
Can you change it to not disappear as we scroll down? @raffoz ( https://github.com/raffoz )

**Comment by kleyv** [comment]
Please do. It' extra work to have to scroll up to access the stuff on the nav bar.

**Comment by raffoz** [comment]
As you desire


On August 27, 2020 at 10:16 AM, kleyv (notifications@github.com) wrote:
Please do. It' extra work to have to scroll up to access the stuff on the nav bar.

**Pull request merged**
