### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by raffoz**
- wrapper spaces: better now
- navbar white after scroll
- different texts if not logged, logged as owner or as investor
- Flo sent me the logo and I put inside

### CODE REVIEW

**Comment by kleyv** [comment]
@raffoz @Flott2410  I prefer the the initial navbar behaviour by the LeWagon kit

**Comment by raffoz** [comment]
> @raffoz @Flott2410 I prefer the the initial navbar behaviour by the LeWagon kit

We do not have time now I think

**Comment by raffoz** [comment]
> @raffoz @Flott2410 I prefer the the initial navbar behaviour by the LeWagon kit

Ok, but we do not have time now to make these design changes (I think)

**Comment by kleyv** [comment]
@raffoz you answered twice and I think you closed the pull request by accident.
Yes you're right, the navbar isn't a priority and can remain as is. The other stuff is more important.

**Comment by raffoz** [comment]
I do not understand :)
I reopened it 

If ok merge
Otherwise tell me what to do tks

**Comment by Flott2410** [comment]
I will merge it ;-)

**Pull request merged**
